## El poder de NumPy

In [ ]:
range(0, 5)

In [ ]:
list(range(0, 5))

In [ ]:
list(range(0, 5, 2))

In [4]:
list1 = [1, 3, 5, 7, 9]
list2 = [2, 4, 6, 8, 10]

In [5]:
list1 * list2

TypeError: can't multiply sequence by non-int of type 'list'

In [6]:
new_list = []

for i in range(0, len(list1)):
    x = list1[i] * list2[i]
    new_list.append(x)

print(new_list)

[2, 12, 30, 56, 90]


In [7]:
import numpy as np

In [8]:
x = np.array([1, 3, 5, 7, 9])
y = np.array([2, 4, 6, 8, 10])

In [ ]:
print(type(x))

In [ ]:
x * y

## Creando un Arreglo NumPy con la Funcion Array()

In [ ]:
import numpy as np

In [ ]:
np.array([2, 4, 6, 8])

In [ ]:
variable = [5.8, 9, 7, 5]

In [ ]:
print(type(variable[0]))
print(type(variable[1]))

In [ ]:
new_variable = np.array([5.8, 9, 7, 5])

In [ ]:
new_variable

In [ ]:
print(type(new_variable[0]))
print(type(new_variable[1]))

In [ ]:
new_variable2 = np.array([5.8, 9, 7, 5], dtype = "int")

In [ ]:
new_variable2

## Creando un Arreglo NumPy con la Funcion Zeros() 

In [ ]:
import numpy as np

In [ ]:
np.zeros(5)

In [ ]:
np.zeros((3, 5), dtype = "int")

## Creando un Arreglo NumPy con la Funcion Ones() 


In [ ]:
import numpy as np

In [ ]:
np.ones(10)

In [ ]:
np.ones((3, 4, 5), dtype = "int")

## Creando un Arreglo NumPy con la Funcion Full()

In [ ]:
import numpy as np

In [ ]:
np.full(8, 5)

In [ ]:
np.full((2, 3), 6, dtype = "float")

## Creando un Arreglo NumPy con la Funcion Arange() 


In [ ]:
import numpy as np

In [ ]:
np.arange(5)

In [ ]:
example = np.arange(3, 10, dtype = "float")

In [ ]:
print(example)

In [ ]:
type(example)

## Creando un Arreglo NumPy con la Funcion Eye() 

In [ ]:
import numpy as np

In [ ]:
np.eye(3)

In [ ]:
np.eye(3, 2)

In [ ]:
np.eye(3, 2, dtype = "bool")

## Creando con el Arreglo NumPy con la Funcion Linspace() 

In [ ]:
import numpy as np

In [ ]:
np.linspace(10, 30, 10)

## Creando Arreglo NumPy con la Funcion Random() 

In [ ]:
import numpy as np

In [ ]:
# rand function
np.random.rand(5)

In [ ]:
np.random.rand(2,3)

In [ ]:
# randn function
np.random.randn(5)

In [ ]:
np.random.randn(2, 3)

In [ ]:
# random.normal function
np.random.normal(20, 5, (4, 3))

In [2]:
# randint function
np.random.randint(0, 10, (4, 4))

NameError: name 'numpy' is not defined

## Propiedades de un Arreglo NumPy 

In [ ]:
import numpy as np

In [ ]:
matrix = np.random.randint(10, 50, (5, 4))

In [ ]:
matrix

In [ ]:
matrix.ndim

In [ ]:
matrix.shape

In [ ]:
matrix.size

In [ ]:
matrix.dtype

## Manipulando un Arreglo NumPy: Funcion Reshape()

In [ ]:
import numpy as np

In [ ]:
example = np.arange(1, 16)

In [ ]:
example

In [ ]:
example.reshape((3, 5))

In [ ]:
array = example.reshape((1, 15))

In [ ]:
array

In [ ]:
example.ndim

In [ ]:
array.ndim

In [ ]:
example

In [ ]:
example.reshape((4, 3))

## Identificando el Mayor Elemento de un Arreglo Numpy: Funciones Max(), Argmax() 

In [ ]:
import numpy as np

In [10]:
array = np.random.randint(0, 50, 10)

In [11]:
array

array([ 9, 40, 19, 34,  6, 16,  5,  8, 32, 33])

In [12]:
array.max()

40

In [13]:
array.argmax()

1

In [14]:
array2 = np.random.randint(0, 50, (4, 3))

In [15]:
array2

array([[42, 16, 39],
       [20, 47, 34],
       [11, 40, 40],
       [10, 37, 12]])

In [16]:
array2.max()

47

In [17]:
array2.argmax()

4

## Detectando el Menor Elemento de un Arreglo Numpy : Funciones Min(), Argmin() 

In [ ]:
import numpy as np

In [ ]:
array = np.random.randint(20, 70, 10)

In [ ]:
array

In [ ]:
array.min()

In [ ]:
array.argmin()

In [ ]:
array2 = np.random.randint(20, 70, (5, 3))

In [ ]:
array2

In [ ]:
array2.min()

In [ ]:
array2.argmin()

## Concatenando Arreglos Numpy: Funcion Concatenate() 

In [ ]:
import numpy as np

In [18]:
array1 = np.array([1, 2, 3, 4])
array2 = np.array([5, 6, 7, 8])

In [19]:
np.concatenate([array1, array2])

array([1, 2, 3, 4, 5, 6, 7, 8])

In [20]:
array3 = np.arange(1, 7).reshape((2, 3))

In [21]:
array3

array([[1, 2, 3],
       [4, 5, 6]])

In [22]:
array4 = np.array([[7, 8, 9], [10, 11, 12]])

In [23]:
array4 

array([[ 7,  8,  9],
       [10, 11, 12]])

In [ ]:
np.concatenate([array3, array4])

In [ ]:
np.concatenate([array3, array4], axis = 1)

In [ ]:
np.concatenate([array1, array3])

In [35]:
array5 = np.arange(1,7).reshape(2 , 3)

In [36]:
array5 

array([[1, 2, 3],
       [4, 5, 6]])

In [39]:
np.concatenate([array3, array5], axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

## Dividiendo Arreglos Uni-Dimensional Numpy : La Funcion Split() 

In [ ]:
import numpy as np

In [ ]:
array = np.array([1, 3, 5, 50, 50 , 2, 4, 6])

In [ ]:
np.split(array, [3, 5])

In [ ]:
x, y, z = np.split(array, [3, 5])

In [ ]:
x

In [ ]:
y

In [ ]:
z

In [ ]:
np.split(array, 4)

In [ ]:
np.split(array, 5)

## Dividiendo Arreglos Bi-Dimensionales Numpy : Funcion Split(), Vsplit, Hsplit() 

In [ ]:
import numpy as np

In [ ]:
array = np.arange(20).reshape(5, 4)

In [ ]:
array

In [ ]:
np.split(array, [1, 3])

In [ ]:
x, y, z = np.split(array, [1, 3])

In [ ]:
x

In [ ]:
y

In [ ]:
z

In [ ]:
np.split(array, [1, 3], axis = 1)

In [ ]:
# hsplit() function

In [ ]:
array

In [ ]:
np.hsplit(array, 4)

In [ ]:
np.hsplit(array, [1, 3]) 

In [ ]:
# vsplit() function

In [ ]:
array

In [ ]:
np.vsplit(array, 5)

In [ ]:
np.vsplit(array, [2, 4])

## Ordenando Arreglos Numpy: Funcion Sort()

In [ ]:
import numpy as np

In [ ]:
variable = np.array([3, 5, 1, 8, 6, 2, 9])

In [ ]:
variable

In [ ]:
np.sort(variable)

In [ ]:
variable

In [ ]:
variable2 = np.sort(variable)

In [ ]:
variable2

In [ ]:
example = np.random.normal(30, 10, (4, 4))

In [ ]:
example

In [ ]:
np.sort(example, axis = 0)

In [ ]:
np.sort(example, axis = 1)